### ISSUE TITLE
[FE] 메뉴 담기 모달

### ISSUE THREAD

**Issue by youzysu** [codesquad-gwanaksan/kiosk-max#10]
## TO-BE
- [x] 모달은 handleAddOrder(menuOrder: MenuOrder) 함수를 props로 전달받는다.
- [x] 담기 버튼을 누르면 handleAddOrder의 인자로 menuOrder를 전달한다.

## Bug
- [x] #40

**Comment by youzysu** [comment]
### 리액트 모달 만드는 방법 참고
1. react-modal 라이브러리
2. https://react-ko.dev/reference/react-dom/createPortal#rendering-a-modal-dialog-with-a-portal
3. https://mingule.tistory.com/78

**Comment by qkdflrgs** [comment]
> 리액트 모달 라이브러리 사용해도 될까?

요구사항에 '리액트 이외 라이브러리 사용 금지'이라는 조건이 있는데, 해당 기능이 리액트 내부적인거라면 사용해도 괜찮지 않을까요??😶

**Comment by youzysu** [comment]
## Current
- 메인 페이지에 모달별로 오픈 상태를 둔다.
- orderModalOpen 상태는 Main 컴포넌트 > 메뉴 아이템 으로 전달하여 클릭 이벤트 핸들러로 전달한다.

## TO-BE
- 메뉴 아이템을 클릭하면 해당 아이디의 메뉴 데이터로 주문 모달
