### ISSUE TITLE
[FE] 기존 메뉴 추가 시 추가되는 메뉴 수량 버그

### ISSUE THREAD

**Issue by youzysu** [codesquad-gwanaksan/kiosk-max#40]

**Comment by qkdflrgs** [comment]
수량으로 넘어가는 데이터 amount는 디버깅 해봤을 때 이상없이 들어가고 있는 것으로 확인되는데 혹시 리듀서의 Add 부분은 이상없나요??

**Comment by youzysu** [comment]
orderList를 하단의 Cart 컴포넌트에 맞는 형태로 가공하는 함수(formatOrderList) 로직 문제였습니다. 리태 확인 감사해요 🙏
