### ISSUE TITLE
[FE] 결제 방식 선택 - 카드결제

### ISSUE THREAD

**Issue by youzysu** [codesquad-gwanaksan/kiosk-max#47]
# 카드결제

## Props
- orderList
- [x] 1. PaymentModal 카드결제 버튼을 클릭하면 1. paymentMethod 상태가 card로 변경된다. = LoadingIndecator 컴포넌트가 렌더링 된다.
- [x] 2. requestCardOrder POST 요청을 보낸다.

## 결제 요청
- [x] requestCardOrder
- [x] `api/payment/card`로 POST Request를 보낸다.
  - orderItems: orderList에 담겨있는 제품을 동일한 menuId, size, temperature 옵션끼리 모은다. (formatOrderList 함수 활용)
  - totalPrice: orderList와 formattedMenus를 받아서 totalPrice를 계산한다. (별도 함수로 구현)

## 로딩 인디케이터
- [x] response가 오기 전까지 로딩 인디케이터가 보여진다.

## 결제 실패 success가 false
- [x] errorCode status가 400이면 message를 유저에게 보여준다.
- [x] errorCode status가 500이면 '서버 에러: 잠시 후 결제를 다시 요청해주세요. 죄송합니다.' 메시지를 보여준다.

## 결제 성공 success가 true이면
- [x] 해당 orderId로 `api/receipt?orderId={orderId}` 요청을 보낸다.
- [x] 해당 orderId의 ReceiptPage로 변경한다.

```
{
"orderId" : 11,
"orderNumber": 3
"orderItems": [
{
	"menuId": 1,
	"size": "large",
	  "temperature" : "hot",
	"amount": 2
},
{
	"menuId": 1,
	"size": "small",
	  "temperature" : "ice",
	"amount": 2
}
{
	"menuId": 1, // 메뉴아이디
	"size": "small", // 크기
	  "temperature" : "hot", // 온도
	"amount": 2 // 개수
}],
"paymentMethod": "card" // 결제방식
"totalPrice": 10000, // 결제금액
"receivedPrice" : 10000, // 투입금액
"remainedPrice" : 0, // 거스름돈
"orderDatetime" : 2023-06-21 12:00:00 // 주문시간
}
```

**Comment by qkdflrgs** [comment]
## 로딩 인디케이터
1. 로딩 인디케이터의 구성
상단: 애니메이션
하단: 문구('카드 결제중...')

2. 로딩 인디케이터로 어떤 애니메이션을 띄울 것인가?
로딩 시간(결제가 완료되고 다음 화면으로 넘어가는 시간)은 서버에서 정해지기 때문에 루프 애니메이션 활용

**Comment by youzysu** [comment]
### 트러블슈팅
- json은 주석 지원을 안하므로 parse 에러 -> 주석 모두 제거해야 한다.
