### ISSUE TITLE
[FE] 키오스크 Client Routing

### ISSUE THREAD

**Issue by youzysu** [codesquad-gwanaksan/kiosk-max#48]
6월 27일 오후 3시

- 어디서 fetchReceipt 작업을 진행해야 할까?
- 특정 orderId의 영수증 페이지를 어떻게 보여줄까?
- Client Routing 처리를 어떻게 해야 할까?

**Comment by youzysu** [comment]
6월 27일 오후 3시
- 어디서 fetchReceipt 작업을 진행해야 할까?
- 특정 orderId의 영수증 페이지를 어떻게 보여줄까?

**Comment by youzysu** [comment]
### ✔️ 1. navigate 함수 직접 구현하기
> 참고: https://react-ko.dev/reference/react/Suspense#suspense

- path에 따라 보여줄 page가 정해지는 Router 만들기

### 2. react-router 라이브러리 [useNavigate](https://reactrouter.com/en/main/hooks/use-navigate), [useParams](https://reactrouter.com/en/main/hooks/use-params)

- Receipt 컴포넌트 내부에서 useParams로 전달받은 receipt id로 데이터 요청해서 만든다.

```ts
function App() {
  return (
    <BrowserRouter>
      <Routes basename="/">
        <Route 
          path={}
          element={<MainPage />} 
        />
        <Route 
          path="/receipt/:id" 
          element={<Receipt />} 
        />
      </Routes>
    </BrowserRouter>
  );
}
```

**Comment by youzysu** [comment]
2. react-router 라이브러리

**Comment by qkdflrgs** [comment]
## Routing 처리를 어떻게 할 것인가?
1. react-router를 받아들인다
2. Router와 같은 역할을 하는 상태(state)를 만든다
- 예시 코드(App.tsx)
```tsx
const App = () => {
  const [routes] = useState([
    { path: "/", page: MainPage },
    { path: "/receipt", page: ReceiptPage }
  ]);

  return (
    <div>
      <Router routes={routes} />
    </div>
  );
};
```
- 예시 코드(Router.tsx)
```tsx
const Router = ({ routes }: RouterProps) => {
  const [currentPath, setCurrentPath] = useState<string>(window.location.pathname);

  const renderPage = () => {
    const route = routes.find((page) => page.path === currentPath);
    if (route) {
      return route.page();
    }
    console.log('Not Found');
  };

  return <div>{renderPage()}</div>;
};
```
