### ISSUE TITLE
[BE] 데이터베이스 스키마 생성

### ISSUE THREAD

**Issue by yonghwankim-dev** [codesquad-gwanaksan/kiosk-max#7]
RDS 환경 구성 완료후 ERD 기반 데이터베이스 생성

**Comment by devbattery** [comment]
<img width="362" alt="스크린샷 2023-06-20 오후 6 04 04" src="https://github.com/codesquad-gwanaksan/kiosk-max/assets/62871026/53b1c292-afc7-405f-b35e-025a6540f5b4">
