### ISSUE TITLE
[FE] 취소 버튼을 클릭하면 재확인하는 작은 모달창이 뜬다.

### ISSUE THREAD

**Issue by youzysu** [codesquad-gwanaksan/kiosk-max#78]
### 메뉴 취소
- [x] '메뉴를 모두 취소하시겠습니까?'

### 결제 취소
- [x] 결제 취소를 재확인하는 모달이 다시 띄워진다.
- '결제를 취소하시겠습니까? '예'를 클릭하면 주문 내역을 모두 비우고 모달이 닫힌다.
- UX 측면에서 결제 취소 시 주문 내역을 모두 비우는 경험이 좋지 않다고 판단하여 모달만 닫히도록 진행
- [x] '아니오'를 클릭하면 해당 모달이 닫힌다.

**Comment by qkdflrgs** [comment]
조이 아래 요구사항은 주문 내역이 비워지는 것보다 남아있는게 사용자 입장에서 좋을 것 같아 구현하지 않았는데 조이는 어떻게 생각하시는지 궁금해요!! 메뉴를 추가하고 싶어서 결제를 취소하는 경우에 주문 내역이 비워지면 불편할 것 같아서요!
- '결제를 취소하시겠습니까? '예'를 클릭하면 주문 내역을 모두 비우고 모달이 닫힌다.

**Comment by youzysu** [comment]
아하, 저도 UX 측면에서는 리태 말씀에 동의합니다! 일단 기획서에 나와있는 내용대로 그대로 작성해뒀었는데, 그럼 그냥 닫는걸로 진행하시죠!
